//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSite.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityArabaEntities1 : DbContext
    {
        public EntityArabaEntities1()
            : base("name=EntityArabaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Ilanlar> Tbl_Ilanlar { get; set; }
        public virtual DbSet<Tbl_Kullancılar> Tbl_Kullancılar { get; set; }
        public virtual DbSet<Tbl_Marka> Tbl_Marka { get; set; }
        public virtual DbSet<Tbl_Modeller> Tbl_Modeller { get; set; }
        public virtual DbSet<Tbl_Reklamlar> Tbl_Reklamlar { get; set; }
        public virtual DbSet<Tbl_Mesajlar> Tbl_Mesajlar { get; set; }
    }
}
