//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SatisUrun
    {
        public short URUNID { get; set; }
        public string URUNADI { get; set; }
        public Nullable<short> URUNSTOK { get; set; }
        public Nullable<decimal> URUNFIYAT { get; set; }
    }
}
